### ISSUE TITLE
Get all posts error: cannnot read property _id of null

### ISSUE THREAD

**Issue by ewerton-azevedo** [webtipsio/backend#2]
```
TypeError: Cannot read property '_id' of null
    at exports.getAllPosts (/app/controllers/blogController.js:26:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

We should be able to get all posts even when not making an authenticated request.
The error above happens because the request comes from a user with no open session.

**Comment by ewerton-azevedo** [comment]
Fixed
